// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/AlarmCenterCallback.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AlarmCenterGrpcServiceLibrary {
  /// <summary>
  ///消息回调接口
  /// </summary>
  public static partial class AlarmCenterCallback
  {
    static readonly string __ServiceName = "AlarmCenterGrpcServiceLibrary.AlarmCenterCallback";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.IntegerDefine> __Marshaller_AlarmCenterGrpcServiceLibrary_IntegerDefine = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.IntegerDefine.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.StringResult> __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.StringResult.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.BoolDefine> __Marshaller_AlarmCenterGrpcServiceLibrary_BoolDefine = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.BoolDefine.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs> __Marshaller_AlarmCenterGrpcServiceLibrary_ProtosEventArgs = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.OpenPageReply> __Marshaller_AlarmCenterGrpcServiceLibrary_OpenPageReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.OpenPageReply.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.ShowPageReply> __Marshaller_AlarmCenterGrpcServiceLibrary_ShowPageReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.ShowPageReply.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.LoginReply> __Marshaller_AlarmCenterGrpcServiceLibrary_LoginReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.LoginReply.Parser));

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Listen = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Listen",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.IntegerDefine, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetInterScreenID = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.IntegerDefine, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetInterScreenID",
        __Marshaller_AlarmCenterGrpcServiceLibrary_IntegerDefine,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringResult, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetGUID = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringResult, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetGUID",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringResult, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetUserNm = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringResult, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetUserNm",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_GetTotalEquipData = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTotalEquipData",
        __Marshaller_AlarmCenterGrpcServiceLibrary_BoolDefine,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_GetTotalYCData = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTotalYCData",
        __Marshaller_AlarmCenterGrpcServiceLibrary_BoolDefine,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_GetTotalYXData = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTotalYXData",
        __Marshaller_AlarmCenterGrpcServiceLibrary_BoolDefine,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_FirstGetRealEventItem = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FirstGetRealEventItem",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_GetRealEventItem = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRealEventItem",
        __Marshaller_AlarmCenterGrpcServiceLibrary_BoolDefine,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs, global::AlarmCenterGrpcServiceLibrary.OpenPageReply> __Method_InterScreenOpenPage = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs, global::AlarmCenterGrpcServiceLibrary.OpenPageReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "InterScreenOpenPage",
        __Marshaller_AlarmCenterGrpcServiceLibrary_ProtosEventArgs,
        __Marshaller_AlarmCenterGrpcServiceLibrary_OpenPageReply);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs, global::AlarmCenterGrpcServiceLibrary.ShowPageReply> __Method_ShowPage = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs, global::AlarmCenterGrpcServiceLibrary.ShowPageReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ShowPage",
        __Marshaller_AlarmCenterGrpcServiceLibrary_ProtosEventArgs,
        __Marshaller_AlarmCenterGrpcServiceLibrary_ShowPageReply);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs, global::AlarmCenterGrpcServiceLibrary.ShowPageReply> __Method_ClosePage = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs, global::AlarmCenterGrpcServiceLibrary.ShowPageReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ClosePage",
        __Marshaller_AlarmCenterGrpcServiceLibrary_ProtosEventArgs,
        __Marshaller_AlarmCenterGrpcServiceLibrary_ShowPageReply);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.LoginReply> __Method_Login = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.LoginReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Login",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AlarmCenterGrpcServiceLibrary_LoginReply);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_PushRealEventItem = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "PushRealEventItem",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_GetAddRealEventItem = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAddRealEventItem",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_GetDelRealEventItem = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDelRealEventItem",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterCallbackReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AlarmCenterCallback</summary>
    [grpc::BindServiceMethod(typeof(AlarmCenterCallback), "BindService")]
    public abstract partial class AlarmCenterCallbackBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Listen(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SetInterScreenID(global::AlarmCenterGrpcServiceLibrary.IntegerDefine request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SetGUID(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SetUserNm(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.StringResult> GetTotalEquipData(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.StringResult> GetTotalYCData(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.StringResult> GetTotalYXData(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.StringResult> FirstGetRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.StringResult> GetRealEventItem(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task InterScreenOpenPage(global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs request, grpc::IServerStreamWriter<global::AlarmCenterGrpcServiceLibrary.OpenPageReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ShowPage(global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs request, grpc::IServerStreamWriter<global::AlarmCenterGrpcServiceLibrary.ShowPageReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ClosePage(global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs request, grpc::IServerStreamWriter<global::AlarmCenterGrpcServiceLibrary.ShowPageReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Login(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::IServerStreamWriter<global::AlarmCenterGrpcServiceLibrary.LoginReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task PushRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::IServerStreamWriter<global::AlarmCenterGrpcServiceLibrary.StringResult> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.StringResult> GetAddRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.StringResult> GetDelRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AlarmCenterCallback</summary>
    public partial class AlarmCenterCallbackClient : grpc::ClientBase<AlarmCenterCallbackClient>
    {
      /// <summary>Creates a new client for AlarmCenterCallback</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AlarmCenterCallbackClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AlarmCenterCallback that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AlarmCenterCallbackClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AlarmCenterCallbackClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AlarmCenterCallbackClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Google.Protobuf.WellKnownTypes.Empty Listen(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Listen(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Listen(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Listen, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ListenAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ListenAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Listen, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SetInterScreenID(global::AlarmCenterGrpcServiceLibrary.IntegerDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetInterScreenID(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SetInterScreenID(global::AlarmCenterGrpcServiceLibrary.IntegerDefine request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetInterScreenID, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SetInterScreenIDAsync(global::AlarmCenterGrpcServiceLibrary.IntegerDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetInterScreenIDAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SetInterScreenIDAsync(global::AlarmCenterGrpcServiceLibrary.IntegerDefine request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetInterScreenID, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SetGUID(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetGUID(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SetGUID(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetGUID, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SetGUIDAsync(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetGUIDAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SetGUIDAsync(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetGUID, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SetUserNm(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetUserNm(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SetUserNm(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetUserNm, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SetUserNmAsync(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetUserNmAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SetUserNmAsync(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetUserNm, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetTotalEquipData(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTotalEquipData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetTotalEquipData(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTotalEquipData, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetTotalEquipDataAsync(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTotalEquipDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetTotalEquipDataAsync(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTotalEquipData, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetTotalYCData(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTotalYCData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetTotalYCData(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTotalYCData, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetTotalYCDataAsync(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTotalYCDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetTotalYCDataAsync(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTotalYCData, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetTotalYXData(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTotalYXData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetTotalYXData(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTotalYXData, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetTotalYXDataAsync(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTotalYXDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetTotalYXDataAsync(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTotalYXData, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult FirstGetRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FirstGetRealEventItem(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult FirstGetRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FirstGetRealEventItem, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> FirstGetRealEventItemAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FirstGetRealEventItemAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> FirstGetRealEventItemAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FirstGetRealEventItem, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetRealEventItem(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRealEventItem(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetRealEventItem(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRealEventItem, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetRealEventItemAsync(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRealEventItemAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetRealEventItemAsync(global::AlarmCenterGrpcServiceLibrary.BoolDefine request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRealEventItem, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.OpenPageReply> InterScreenOpenPage(global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InterScreenOpenPage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.OpenPageReply> InterScreenOpenPage(global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_InterScreenOpenPage, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.ShowPageReply> ShowPage(global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShowPage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.ShowPageReply> ShowPage(global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ShowPage, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.ShowPageReply> ClosePage(global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ClosePage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.ShowPageReply> ClosePage(global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ClosePage, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.LoginReply> Login(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.LoginReply> Login(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Login, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.StringResult> PushRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PushRealEventItem(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.StringResult> PushRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_PushRealEventItem, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetAddRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAddRealEventItem(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetAddRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAddRealEventItem, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetAddRealEventItemAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAddRealEventItemAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetAddRealEventItemAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAddRealEventItem, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetDelRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDelRealEventItem(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult GetDelRealEventItem(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDelRealEventItem, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetDelRealEventItemAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDelRealEventItemAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> GetDelRealEventItemAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDelRealEventItem, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AlarmCenterCallbackClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AlarmCenterCallbackClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AlarmCenterCallbackBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Listen, serviceImpl.Listen)
          .AddMethod(__Method_SetInterScreenID, serviceImpl.SetInterScreenID)
          .AddMethod(__Method_SetGUID, serviceImpl.SetGUID)
          .AddMethod(__Method_SetUserNm, serviceImpl.SetUserNm)
          .AddMethod(__Method_GetTotalEquipData, serviceImpl.GetTotalEquipData)
          .AddMethod(__Method_GetTotalYCData, serviceImpl.GetTotalYCData)
          .AddMethod(__Method_GetTotalYXData, serviceImpl.GetTotalYXData)
          .AddMethod(__Method_FirstGetRealEventItem, serviceImpl.FirstGetRealEventItem)
          .AddMethod(__Method_GetRealEventItem, serviceImpl.GetRealEventItem)
          .AddMethod(__Method_InterScreenOpenPage, serviceImpl.InterScreenOpenPage)
          .AddMethod(__Method_ShowPage, serviceImpl.ShowPage)
          .AddMethod(__Method_ClosePage, serviceImpl.ClosePage)
          .AddMethod(__Method_Login, serviceImpl.Login)
          .AddMethod(__Method_PushRealEventItem, serviceImpl.PushRealEventItem)
          .AddMethod(__Method_GetAddRealEventItem, serviceImpl.GetAddRealEventItem)
          .AddMethod(__Method_GetDelRealEventItem, serviceImpl.GetDelRealEventItem).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AlarmCenterCallbackBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Listen, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Listen));
      serviceBinder.AddMethod(__Method_SetInterScreenID, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.IntegerDefine, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SetInterScreenID));
      serviceBinder.AddMethod(__Method_SetGUID, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringResult, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SetGUID));
      serviceBinder.AddMethod(__Method_SetUserNm, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringResult, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SetUserNm));
      serviceBinder.AddMethod(__Method_GetTotalEquipData, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.GetTotalEquipData));
      serviceBinder.AddMethod(__Method_GetTotalYCData, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.GetTotalYCData));
      serviceBinder.AddMethod(__Method_GetTotalYXData, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.GetTotalYXData));
      serviceBinder.AddMethod(__Method_FirstGetRealEventItem, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.FirstGetRealEventItem));
      serviceBinder.AddMethod(__Method_GetRealEventItem, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.BoolDefine, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.GetRealEventItem));
      serviceBinder.AddMethod(__Method_InterScreenOpenPage, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs, global::AlarmCenterGrpcServiceLibrary.OpenPageReply>(serviceImpl.InterScreenOpenPage));
      serviceBinder.AddMethod(__Method_ShowPage, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs, global::AlarmCenterGrpcServiceLibrary.ShowPageReply>(serviceImpl.ShowPage));
      serviceBinder.AddMethod(__Method_ClosePage, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.ProtosEventArgs, global::AlarmCenterGrpcServiceLibrary.ShowPageReply>(serviceImpl.ClosePage));
      serviceBinder.AddMethod(__Method_Login, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.LoginReply>(serviceImpl.Login));
      serviceBinder.AddMethod(__Method_PushRealEventItem, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.PushRealEventItem));
      serviceBinder.AddMethod(__Method_GetAddRealEventItem, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.GetAddRealEventItem));
      serviceBinder.AddMethod(__Method_GetDelRealEventItem, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.GetDelRealEventItem));
    }

  }
}
#endregion
