// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/AlarmCenterDatabase.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AlarmCenterGrpcServiceLibrary {

  /// <summary>Holder for reflection information generated from proto/AlarmCenterDatabase.proto</summary>
  public static partial class AlarmCenterDatabaseReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/AlarmCenterDatabase.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AlarmCenterDatabaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9wcm90by9BbGFybUNlbnRlckRhdGFiYXNlLnByb3RvEh1BbGFybUNlbnRl",
            "ckdycGNTZXJ2aWNlTGlicmFyeRobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnBy",
            "b3RvGhJwcm90by9jb21tb24ucHJvdG8iHgoORGF0YVRhYmxlUmVwbHkSDAoE",
            "ZGF0YRgBIAEoCSIfCg1TdHJpbmdSZXF1ZXN0Eg4KBnN0clNRTBgBIAEoCSIn",
            "ChVHZXRPYmplY3RGcm9tU1FMUmVwbHkSDgoGb2JqZWN0GAEgASgJIjMKD0Vx",
            "dWlwU3RhUmVxdWVzdBIOCgZzdGFfbm8YASABKAUSEAoIZXF1aXBfbm8YAiAB",
            "KAUiIAoOSW50ZWdlclJlcXVlc3QSDgoGcmVzdWx0GAEgASgFIiMKEFN0cmlu",
            "Z0FyclJlcXVlc3QSDwoHcmVxdWVzdBgBIAMoCSJTCh1EYXRhUmVjb3JkUXVl",
            "cnlGcm9tWE1MUmVxdWVzdBIWCg5kaWNFcXVpcFljWXhObxgBIAEoCRIMCgRi",
            "Z25UGAIgASgJEgwKBGVuZFQYAyABKAkiugEKFEdldERhdGFiYXNlVHlwZVJl",
            "cGx5ElYKDGRhdGFiYXNlVHlwZRgBIAEoDjJALkFsYXJtQ2VudGVyR3JwY1Nl",
            "cnZpY2VMaWJyYXJ5LkdldERhdGFiYXNlVHlwZVJlcGx5LkRhdGFiYXNlVHlw",
            "ZSJKCgxEYXRhYmFzZVR5cGUSCgoGQWNjZXNzEAASDQoJU1FMU2VydmVyEAES",
            "CgoGU1FMaXRlEAISCQoFTXlTcWwQAxIICgRPREJDEAQiHgoOQnl0ZUFyclJl",
            "cXVlc3QSDAoEZGF0YRgBIAMoDCI5ChRFeGVjdXRlSW5zZXJ0U1FMUGFybRIO",
            "CgZzdHJTcWwYASABKAkSEQoJdGFibGVOYW1lGAIgASgJMrUSChNBbGFybUNl",
            "bnRlckRhdGFiYXNlElwKE0dldERhdGFUYWJsZU9mRXF1aXASFi5nb29nbGUu",
            "cHJvdG9idWYuRW1wdHkaLS5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFy",
            "eS5EYXRhVGFibGVSZXBseRJ2ChBHZXRPYmplY3RGcm9tU1FMEiwuQWxhcm1D",
            "ZW50ZXJHcnBjU2VydmljZUxpYnJhcnkuU3RyaW5nUmVxdWVzdBo0LkFsYXJt",
            "Q2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LkdldE9iamVjdEZyb21TUUxSZXBs",
            "eRJyChFHZXREYXRhVGFibGVPZllDUBIuLkFsYXJtQ2VudGVyR3JwY1NlcnZp",
            "Y2VMaWJyYXJ5LkVxdWlwU3RhUmVxdWVzdBotLkFsYXJtQ2VudGVyR3JwY1Nl",
            "cnZpY2VMaWJyYXJ5LkRhdGFUYWJsZVJlcGx5EnIKEUdldERhdGFUYWJsZU9m",
            "WVhQEi4uQWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnkuRXF1aXBTdGFS",
            "ZXF1ZXN0Gi0uQWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnkuRGF0YVRh",
            "YmxlUmVwbHkSdgoVR2V0RGF0YVRhYmxlT2ZTZXRQYXJtEi4uQWxhcm1DZW50",
            "ZXJHcnBjU2VydmljZUxpYnJhcnkuRXF1aXBTdGFSZXF1ZXN0Gi0uQWxhcm1D",
            "ZW50ZXJHcnBjU2VydmljZUxpYnJhcnkuRGF0YVRhYmxlUmVwbHkScgoTR2V0",
            "RGF0YVRhYmxlRnJvbVNRTBIsLkFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJy",
            "YXJ5LlN0cmluZ1JlcXVlc3QaLS5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGli",
            "cmFyeS5EYXRhVGFibGVSZXBseRJdChVHZXREYXRhVGFibGVGcm9tU1FMRXgS",
            "LC5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5TdHJpbmdSZXF1ZXN0",
            "GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5El4KFkdldERhdGFUYWJsZUZyb21T",
            "UUxFeDESLC5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5TdHJpbmdS",
            "ZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5ElYKDkdldERhdGFBZGFw",
            "dGVyEiwuQWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnkuU3RyaW5nUmVx",
            "dWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRJlChxTYXZlRGF0YVRhYmxl",
            "V2l0aERhdGFBZGFwdGVyEi0uQWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJh",
            "cnkuRGF0YVRhYmxlUmVwbHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSaQoK",
            "RXhlY3V0ZVNRTBIsLkFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LlN0",
            "cmluZ1JlcXVlc3QaLS5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5J",
            "bnRlZ2VyUmVxdWVzdBJ2ChBFeGVjdXRlSW5zZXJ0U1FMEjMuQWxhcm1DZW50",
            "ZXJHcnBjU2VydmljZUxpYnJhcnkuRXhlY3V0ZUluc2VydFNRTFBhcm0aLS5B",
            "bGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5JbnRlZ2VyUmVxdWVzdBJl",
            "ChpFeGVjdXRlU1FMc1dpdGhUcmFuc2FjdGlvbhIvLkFsYXJtQ2VudGVyR3Jw",
            "Y1NlcnZpY2VMaWJyYXJ5LlN0cmluZ0FyclJlcXVlc3QaFi5nb29nbGUucHJv",
            "dG9idWYuRW1wdHkSOAoGTGlzdGVuEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5",
            "GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EkoKBUxvZ2luEikuQWxhcm1DZW50",
            "ZXJHcnBjU2VydmljZUxpYnJhcnkuTG9naW5Nb2RlbBoWLmdvb2dsZS5wcm90",
            "b2J1Zi5FbXB0eRI+CgxDbG9zZVNlc3Npb24SFi5nb29nbGUucHJvdG9idWYu",
            "RW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSgQEKFkRhdGFSZWNvcmRR",
            "dWVyeUZyb21YTUwSPC5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5E",
            "YXRhUmVjb3JkUXVlcnlGcm9tWE1MUmVxdWVzdBopLkFsYXJtQ2VudGVyR3Jw",
            "Y1NlcnZpY2VMaWJyYXJ5LkJhc2VSZXN1bHQSbwoQT3BlblJlYWRGcm9tRmls",
            "ZRIsLkFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LlN0cmluZ1JlcXVl",
            "c3QaLS5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5CeXRlQXJyUmVx",
            "dWVzdBJzChRSZWFkQWxsQnl0ZXNGcm9tRmlsZRIsLkFsYXJtQ2VudGVyR3Jw",
            "Y1NlcnZpY2VMaWJyYXJ5LlN0cmluZ1JlcXVlc3QaLS5BbGFybUNlbnRlckdy",
            "cGNTZXJ2aWNlTGlicmFyeS5CeXRlQXJyUmVxdWVzdBJTCg5SZWFkTmV4dEJ1",
            "ZmZlchIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRopLkFsYXJtQ2VudGVyR3Jw",
            "Y1NlcnZpY2VMaWJyYXJ5LkJvb2xEZWZpbmUSWQoQR2V0Q3VycmVudEJ1ZmZl",
            "chIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRotLkFsYXJtQ2VudGVyR3JwY1Nl",
            "cnZpY2VMaWJyYXJ5LkJ5dGVBcnJSZXF1ZXN0El4KD0dldERhdGFiYXNlVHlw",
            "ZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRozLkFsYXJtQ2VudGVyR3JwY1Nl",
            "cnZpY2VMaWJyYXJ5LkdldERhdGFiYXNlVHlwZVJlcGx5EmwKEUdldERhdGFQ",
            "YWdpbmF0aW9uEiwuQWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnkuU3Ry",
            "aW5nUmVxdWVzdBopLkFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LkJh",
            "c2VSZXN1bHRCIKoCHUFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5YgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::AlarmCenterGrpcServiceLibrary.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.DataTableReply), global::AlarmCenterGrpcServiceLibrary.DataTableReply.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.StringRequest), global::AlarmCenterGrpcServiceLibrary.StringRequest.Parser, new[]{ "StrSQL" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply), global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply.Parser, new[]{ "Object" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest), global::AlarmCenterGrpcServiceLibrary.EquipStaRequest.Parser, new[]{ "StaNo", "EquipNo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.IntegerRequest), global::AlarmCenterGrpcServiceLibrary.IntegerRequest.Parser, new[]{ "Result" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.StringArrRequest), global::AlarmCenterGrpcServiceLibrary.StringArrRequest.Parser, new[]{ "Request" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest), global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest.Parser, new[]{ "DicEquipYcYxNo", "BgnT", "EndT" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply), global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Parser, new[]{ "DatabaseType" }, null, new[]{ typeof(global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.ByteArrRequest), global::AlarmCenterGrpcServiceLibrary.ByteArrRequest.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm), global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm.Parser, new[]{ "StrSql", "TableName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DataTableReply : pb::IMessage<DataTableReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DataTableReply> _parser = new pb::MessageParser<DataTableReply>(() => new DataTableReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataTableReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataTableReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataTableReply(DataTableReply other) : this() {
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataTableReply Clone() {
      return new DataTableReply(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private string data_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataTableReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataTableReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataTableReply other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Data = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StringRequest : pb::IMessage<StringRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StringRequest> _parser = new pb::MessageParser<StringRequest>(() => new StringRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StringRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringRequest(StringRequest other) : this() {
      strSQL_ = other.strSQL_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringRequest Clone() {
      return new StringRequest(this);
    }

    /// <summary>Field number for the "strSQL" field.</summary>
    public const int StrSQLFieldNumber = 1;
    private string strSQL_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StrSQL {
      get { return strSQL_; }
      set {
        strSQL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StringRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StringRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StrSQL != other.StrSQL) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StrSQL.Length != 0) hash ^= StrSQL.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StrSQL.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StrSQL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StrSQL.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StrSQL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StrSQL.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrSQL);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StringRequest other) {
      if (other == null) {
        return;
      }
      if (other.StrSQL.Length != 0) {
        StrSQL = other.StrSQL;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StrSQL = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            StrSQL = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetObjectFromSQLReply : pb::IMessage<GetObjectFromSQLReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetObjectFromSQLReply> _parser = new pb::MessageParser<GetObjectFromSQLReply>(() => new GetObjectFromSQLReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetObjectFromSQLReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetObjectFromSQLReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetObjectFromSQLReply(GetObjectFromSQLReply other) : this() {
      object_ = other.object_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetObjectFromSQLReply Clone() {
      return new GetObjectFromSQLReply(this);
    }

    /// <summary>Field number for the "object" field.</summary>
    public const int ObjectFieldNumber = 1;
    private string object_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Object {
      get { return object_; }
      set {
        object_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetObjectFromSQLReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetObjectFromSQLReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Object != other.Object) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Object.Length != 0) hash ^= Object.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Object.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Object);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Object.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Object);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Object.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Object);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetObjectFromSQLReply other) {
      if (other == null) {
        return;
      }
      if (other.Object.Length != 0) {
        Object = other.Object;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Object = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Object = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EquipStaRequest : pb::IMessage<EquipStaRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EquipStaRequest> _parser = new pb::MessageParser<EquipStaRequest>(() => new EquipStaRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EquipStaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EquipStaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EquipStaRequest(EquipStaRequest other) : this() {
      staNo_ = other.staNo_;
      equipNo_ = other.equipNo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EquipStaRequest Clone() {
      return new EquipStaRequest(this);
    }

    /// <summary>Field number for the "sta_no" field.</summary>
    public const int StaNoFieldNumber = 1;
    private int staNo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StaNo {
      get { return staNo_; }
      set {
        staNo_ = value;
      }
    }

    /// <summary>Field number for the "equip_no" field.</summary>
    public const int EquipNoFieldNumber = 2;
    private int equipNo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EquipNo {
      get { return equipNo_; }
      set {
        equipNo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EquipStaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EquipStaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StaNo != other.StaNo) return false;
      if (EquipNo != other.EquipNo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StaNo != 0) hash ^= StaNo.GetHashCode();
      if (EquipNo != 0) hash ^= EquipNo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StaNo != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StaNo);
      }
      if (EquipNo != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EquipNo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StaNo != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StaNo);
      }
      if (EquipNo != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EquipNo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StaNo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StaNo);
      }
      if (EquipNo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EquipNo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EquipStaRequest other) {
      if (other == null) {
        return;
      }
      if (other.StaNo != 0) {
        StaNo = other.StaNo;
      }
      if (other.EquipNo != 0) {
        EquipNo = other.EquipNo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StaNo = input.ReadInt32();
            break;
          }
          case 16: {
            EquipNo = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StaNo = input.ReadInt32();
            break;
          }
          case 16: {
            EquipNo = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class IntegerRequest : pb::IMessage<IntegerRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IntegerRequest> _parser = new pb::MessageParser<IntegerRequest>(() => new IntegerRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IntegerRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IntegerRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IntegerRequest(IntegerRequest other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IntegerRequest Clone() {
      return new IntegerRequest(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private int result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IntegerRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IntegerRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IntegerRequest other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StringArrRequest : pb::IMessage<StringArrRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StringArrRequest> _parser = new pb::MessageParser<StringArrRequest>(() => new StringArrRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StringArrRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringArrRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringArrRequest(StringArrRequest other) : this() {
      request_ = other.request_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringArrRequest Clone() {
      return new StringArrRequest(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_request_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> request_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Request {
      get { return request_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StringArrRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StringArrRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!request_.Equals(other.request_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= request_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      request_.WriteTo(output, _repeated_request_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      request_.WriteTo(ref output, _repeated_request_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += request_.CalculateSize(_repeated_request_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StringArrRequest other) {
      if (other == null) {
        return;
      }
      request_.Add(other.request_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            request_.AddEntriesFrom(input, _repeated_request_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            request_.AddEntriesFrom(ref input, _repeated_request_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DataRecordQueryFromXMLRequest : pb::IMessage<DataRecordQueryFromXMLRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DataRecordQueryFromXMLRequest> _parser = new pb::MessageParser<DataRecordQueryFromXMLRequest>(() => new DataRecordQueryFromXMLRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataRecordQueryFromXMLRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataRecordQueryFromXMLRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataRecordQueryFromXMLRequest(DataRecordQueryFromXMLRequest other) : this() {
      dicEquipYcYxNo_ = other.dicEquipYcYxNo_;
      bgnT_ = other.bgnT_;
      endT_ = other.endT_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataRecordQueryFromXMLRequest Clone() {
      return new DataRecordQueryFromXMLRequest(this);
    }

    /// <summary>Field number for the "dicEquipYcYxNo" field.</summary>
    public const int DicEquipYcYxNoFieldNumber = 1;
    private string dicEquipYcYxNo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DicEquipYcYxNo {
      get { return dicEquipYcYxNo_; }
      set {
        dicEquipYcYxNo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bgnT" field.</summary>
    public const int BgnTFieldNumber = 2;
    private string bgnT_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BgnT {
      get { return bgnT_; }
      set {
        bgnT_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endT" field.</summary>
    public const int EndTFieldNumber = 3;
    private string endT_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EndT {
      get { return endT_; }
      set {
        endT_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataRecordQueryFromXMLRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataRecordQueryFromXMLRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DicEquipYcYxNo != other.DicEquipYcYxNo) return false;
      if (BgnT != other.BgnT) return false;
      if (EndT != other.EndT) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DicEquipYcYxNo.Length != 0) hash ^= DicEquipYcYxNo.GetHashCode();
      if (BgnT.Length != 0) hash ^= BgnT.GetHashCode();
      if (EndT.Length != 0) hash ^= EndT.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DicEquipYcYxNo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DicEquipYcYxNo);
      }
      if (BgnT.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BgnT);
      }
      if (EndT.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EndT);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DicEquipYcYxNo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DicEquipYcYxNo);
      }
      if (BgnT.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BgnT);
      }
      if (EndT.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EndT);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DicEquipYcYxNo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DicEquipYcYxNo);
      }
      if (BgnT.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BgnT);
      }
      if (EndT.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndT);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataRecordQueryFromXMLRequest other) {
      if (other == null) {
        return;
      }
      if (other.DicEquipYcYxNo.Length != 0) {
        DicEquipYcYxNo = other.DicEquipYcYxNo;
      }
      if (other.BgnT.Length != 0) {
        BgnT = other.BgnT;
      }
      if (other.EndT.Length != 0) {
        EndT = other.EndT;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DicEquipYcYxNo = input.ReadString();
            break;
          }
          case 18: {
            BgnT = input.ReadString();
            break;
          }
          case 26: {
            EndT = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DicEquipYcYxNo = input.ReadString();
            break;
          }
          case 18: {
            BgnT = input.ReadString();
            break;
          }
          case 26: {
            EndT = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetDatabaseTypeReply : pb::IMessage<GetDatabaseTypeReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetDatabaseTypeReply> _parser = new pb::MessageParser<GetDatabaseTypeReply>(() => new GetDatabaseTypeReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetDatabaseTypeReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetDatabaseTypeReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetDatabaseTypeReply(GetDatabaseTypeReply other) : this() {
      databaseType_ = other.databaseType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetDatabaseTypeReply Clone() {
      return new GetDatabaseTypeReply(this);
    }

    /// <summary>Field number for the "databaseType" field.</summary>
    public const int DatabaseTypeFieldNumber = 1;
    private global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType databaseType_ = global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType.Access;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType DatabaseType {
      get { return databaseType_; }
      set {
        databaseType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetDatabaseTypeReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetDatabaseTypeReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DatabaseType != other.DatabaseType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DatabaseType != global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType.Access) hash ^= DatabaseType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DatabaseType != global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType.Access) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DatabaseType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DatabaseType != global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType.Access) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DatabaseType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DatabaseType != global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType.Access) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DatabaseType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetDatabaseTypeReply other) {
      if (other == null) {
        return;
      }
      if (other.DatabaseType != global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType.Access) {
        DatabaseType = other.DatabaseType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DatabaseType = (global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DatabaseType = (global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Types.DatabaseType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GetDatabaseTypeReply message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum DatabaseType {
        [pbr::OriginalName("Access")] Access = 0,
        [pbr::OriginalName("SQLServer")] Sqlserver = 1,
        [pbr::OriginalName("SQLite")] Sqlite = 2,
        [pbr::OriginalName("MySql")] MySql = 3,
        [pbr::OriginalName("ODBC")] Odbc = 4,
      }

    }
    #endregion

  }

  public sealed partial class ByteArrRequest : pb::IMessage<ByteArrRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ByteArrRequest> _parser = new pb::MessageParser<ByteArrRequest>(() => new ByteArrRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ByteArrRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ByteArrRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ByteArrRequest(ByteArrRequest other) : this() {
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ByteArrRequest Clone() {
      return new ByteArrRequest(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_data_codec
        = pb::FieldCodec.ForBytes(10);
    private readonly pbc::RepeatedField<pb::ByteString> data_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<pb::ByteString> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ByteArrRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ByteArrRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!data_.Equals(other.data_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= data_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      data_.WriteTo(output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      data_.WriteTo(ref output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_repeated_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ByteArrRequest other) {
      if (other == null) {
        return;
      }
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            data_.AddEntriesFrom(ref input, _repeated_data_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExecuteInsertSQLParm : pb::IMessage<ExecuteInsertSQLParm>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExecuteInsertSQLParm> _parser = new pb::MessageParser<ExecuteInsertSQLParm>(() => new ExecuteInsertSQLParm());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExecuteInsertSQLParm> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecuteInsertSQLParm() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecuteInsertSQLParm(ExecuteInsertSQLParm other) : this() {
      strSql_ = other.strSql_;
      tableName_ = other.tableName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecuteInsertSQLParm Clone() {
      return new ExecuteInsertSQLParm(this);
    }

    /// <summary>Field number for the "strSql" field.</summary>
    public const int StrSqlFieldNumber = 1;
    private string strSql_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StrSql {
      get { return strSql_; }
      set {
        strSql_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tableName" field.</summary>
    public const int TableNameFieldNumber = 2;
    private string tableName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TableName {
      get { return tableName_; }
      set {
        tableName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExecuteInsertSQLParm);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExecuteInsertSQLParm other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StrSql != other.StrSql) return false;
      if (TableName != other.TableName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StrSql.Length != 0) hash ^= StrSql.GetHashCode();
      if (TableName.Length != 0) hash ^= TableName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StrSql.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StrSql);
      }
      if (TableName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TableName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StrSql.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StrSql);
      }
      if (TableName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TableName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StrSql.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrSql);
      }
      if (TableName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TableName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExecuteInsertSQLParm other) {
      if (other == null) {
        return;
      }
      if (other.StrSql.Length != 0) {
        StrSql = other.StrSql;
      }
      if (other.TableName.Length != 0) {
        TableName = other.TableName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StrSql = input.ReadString();
            break;
          }
          case 18: {
            TableName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            StrSql = input.ReadString();
            break;
          }
          case 18: {
            TableName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
