// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/AlarmCenterDatabase.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AlarmCenterGrpcServiceLibrary {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class AlarmCenterDatabase
  {
    static readonly string __ServiceName = "AlarmCenterGrpcServiceLibrary.AlarmCenterDatabase";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.DataTableReply> __Marshaller_AlarmCenterGrpcServiceLibrary_DataTableReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.DataTableReply.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.StringRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.StringRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply> __Marshaller_AlarmCenterGrpcServiceLibrary_GetObjectFromSQLReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_EquipStaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.EquipStaRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.IntegerRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_IntegerRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.IntegerRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm> __Marshaller_AlarmCenterGrpcServiceLibrary_ExecuteInsertSQLParm = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.StringArrRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_StringArrRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.StringArrRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.LoginModel> __Marshaller_AlarmCenterGrpcServiceLibrary_LoginModel = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.LoginModel.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_DataRecordQueryFromXMLRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.BaseResult> __Marshaller_AlarmCenterGrpcServiceLibrary_BaseResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.BaseResult.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_ByteArrRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.BoolDefine> __Marshaller_AlarmCenterGrpcServiceLibrary_BoolDefine = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.BoolDefine.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply> __Marshaller_AlarmCenterGrpcServiceLibrary_GetDatabaseTypeReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply.Parser));

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.DataTableReply> __Method_GetDataTableOfEquip = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDataTableOfEquip",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AlarmCenterGrpcServiceLibrary_DataTableReply);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply> __Method_GetObjectFromSQL = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetObjectFromSQL",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_GetObjectFromSQLReply);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply> __Method_GetDataTableOfYCP = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDataTableOfYCP",
        __Marshaller_AlarmCenterGrpcServiceLibrary_EquipStaRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_DataTableReply);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply> __Method_GetDataTableOfYXP = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDataTableOfYXP",
        __Marshaller_AlarmCenterGrpcServiceLibrary_EquipStaRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_DataTableReply);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply> __Method_GetDataTableOfSetParm = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDataTableOfSetParm",
        __Marshaller_AlarmCenterGrpcServiceLibrary_EquipStaRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_DataTableReply);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply> __Method_GetDataTableFromSQL = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDataTableFromSQL",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_DataTableReply);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_GetDataTableFromSQLEx = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDataTableFromSQLEx",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_GetDataTableFromSQLEx1 = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDataTableFromSQLEx1",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_GetDataAdapter = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDataAdapter",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.DataTableReply, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SaveDataTableWithDataAdapter = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.DataTableReply, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveDataTableWithDataAdapter",
        __Marshaller_AlarmCenterGrpcServiceLibrary_DataTableReply,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.IntegerRequest> __Method_ExecuteSQL = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.IntegerRequest>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ExecuteSQL",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_IntegerRequest);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm, global::AlarmCenterGrpcServiceLibrary.IntegerRequest> __Method_ExecuteInsertSQL = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm, global::AlarmCenterGrpcServiceLibrary.IntegerRequest>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ExecuteInsertSQL",
        __Marshaller_AlarmCenterGrpcServiceLibrary_ExecuteInsertSQLParm,
        __Marshaller_AlarmCenterGrpcServiceLibrary_IntegerRequest);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringArrRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ExecuteSQLsWithTransaction = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringArrRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ExecuteSQLsWithTransaction",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringArrRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Listen = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Listen",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.LoginModel, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Login = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.LoginModel, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_AlarmCenterGrpcServiceLibrary_LoginModel,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CloseSession = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CloseSession",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest, global::AlarmCenterGrpcServiceLibrary.BaseResult> __Method_DataRecordQueryFromXML = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest, global::AlarmCenterGrpcServiceLibrary.BaseResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DataRecordQueryFromXML",
        __Marshaller_AlarmCenterGrpcServiceLibrary_DataRecordQueryFromXMLRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_BaseResult);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> __Method_OpenReadFromFile = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest>(
        grpc::MethodType.Unary,
        __ServiceName,
        "OpenReadFromFile",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_ByteArrRequest);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> __Method_ReadAllBytesFromFile = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReadAllBytesFromFile",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_ByteArrRequest);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.BoolDefine> __Method_ReadNextBuffer = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.BoolDefine>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReadNextBuffer",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AlarmCenterGrpcServiceLibrary_BoolDefine);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> __Method_GetCurrentBuffer = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCurrentBuffer",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AlarmCenterGrpcServiceLibrary_ByteArrRequest);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply> __Method_GetDatabaseType = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDatabaseType",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AlarmCenterGrpcServiceLibrary_GetDatabaseTypeReply);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.BaseResult> __Method_GetDataPagination = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.BaseResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDataPagination",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_BaseResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterDatabaseReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AlarmCenterDatabase</summary>
    [grpc::BindServiceMethod(typeof(AlarmCenterDatabase), "BindService")]
    public abstract partial class AlarmCenterDatabaseBase
    {
      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfEquip(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply> GetObjectFromSQL(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfYCP(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfYXP(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfSetParm(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableFromSQL(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> GetDataTableFromSQLEx(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> GetDataTableFromSQLEx1(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> GetDataAdapter(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SaveDataTableWithDataAdapter(global::AlarmCenterGrpcServiceLibrary.DataTableReply request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.IntegerRequest> ExecuteSQL(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.IntegerRequest> ExecuteInsertSQL(global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> ExecuteSQLsWithTransaction(global::AlarmCenterGrpcServiceLibrary.StringArrRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Listen(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Login(global::AlarmCenterGrpcServiceLibrary.LoginModel request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> CloseSession(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.BaseResult> DataRecordQueryFromXML(global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> OpenReadFromFile(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> ReadAllBytesFromFile(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.BoolDefine> ReadNextBuffer(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> GetCurrentBuffer(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///rpc SetGUID (StringRequest) returns (google.protobuf.Empty);
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply> GetDatabaseType(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.BaseResult> GetDataPagination(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AlarmCenterDatabase</summary>
    public partial class AlarmCenterDatabaseClient : grpc::ClientBase<AlarmCenterDatabaseClient>
    {
      /// <summary>Creates a new client for AlarmCenterDatabase</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AlarmCenterDatabaseClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AlarmCenterDatabase that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AlarmCenterDatabaseClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AlarmCenterDatabaseClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AlarmCenterDatabaseClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableOfEquip(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableOfEquip(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableOfEquip(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDataTableOfEquip, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfEquipAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableOfEquipAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfEquipAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDataTableOfEquip, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply GetObjectFromSQL(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetObjectFromSQL(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply GetObjectFromSQL(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetObjectFromSQL, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply> GetObjectFromSQLAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetObjectFromSQLAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply> GetObjectFromSQLAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetObjectFromSQL, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableOfYCP(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableOfYCP(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableOfYCP(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDataTableOfYCP, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfYCPAsync(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableOfYCPAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfYCPAsync(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDataTableOfYCP, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableOfYXP(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableOfYXP(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableOfYXP(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDataTableOfYXP, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfYXPAsync(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableOfYXPAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfYXPAsync(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDataTableOfYXP, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableOfSetParm(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableOfSetParm(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableOfSetParm(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDataTableOfSetParm, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfSetParmAsync(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableOfSetParmAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableOfSetParmAsync(global::AlarmCenterGrpcServiceLibrary.EquipStaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDataTableOfSetParm, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableFromSQL(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableFromSQL(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.DataTableReply GetDataTableFromSQL(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDataTableFromSQL, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableFromSQLAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableFromSQLAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.DataTableReply> GetDataTableFromSQLAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDataTableFromSQL, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GetDataTableFromSQLEx(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableFromSQLEx(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GetDataTableFromSQLEx(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDataTableFromSQLEx, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GetDataTableFromSQLExAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableFromSQLExAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GetDataTableFromSQLExAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDataTableFromSQLEx, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GetDataTableFromSQLEx1(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableFromSQLEx1(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GetDataTableFromSQLEx1(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDataTableFromSQLEx1, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GetDataTableFromSQLEx1Async(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataTableFromSQLEx1Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GetDataTableFromSQLEx1Async(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDataTableFromSQLEx1, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GetDataAdapter(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataAdapter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GetDataAdapter(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDataAdapter, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GetDataAdapterAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataAdapterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GetDataAdapterAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDataAdapter, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SaveDataTableWithDataAdapter(global::AlarmCenterGrpcServiceLibrary.DataTableReply request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveDataTableWithDataAdapter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SaveDataTableWithDataAdapter(global::AlarmCenterGrpcServiceLibrary.DataTableReply request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveDataTableWithDataAdapter, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SaveDataTableWithDataAdapterAsync(global::AlarmCenterGrpcServiceLibrary.DataTableReply request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveDataTableWithDataAdapterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SaveDataTableWithDataAdapterAsync(global::AlarmCenterGrpcServiceLibrary.DataTableReply request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveDataTableWithDataAdapter, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.IntegerRequest ExecuteSQL(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExecuteSQL(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.IntegerRequest ExecuteSQL(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExecuteSQL, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.IntegerRequest> ExecuteSQLAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExecuteSQLAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.IntegerRequest> ExecuteSQLAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExecuteSQL, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.IntegerRequest ExecuteInsertSQL(global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExecuteInsertSQL(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.IntegerRequest ExecuteInsertSQL(global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExecuteInsertSQL, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.IntegerRequest> ExecuteInsertSQLAsync(global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExecuteInsertSQLAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.IntegerRequest> ExecuteInsertSQLAsync(global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExecuteInsertSQL, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty ExecuteSQLsWithTransaction(global::AlarmCenterGrpcServiceLibrary.StringArrRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExecuteSQLsWithTransaction(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty ExecuteSQLsWithTransaction(global::AlarmCenterGrpcServiceLibrary.StringArrRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExecuteSQLsWithTransaction, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ExecuteSQLsWithTransactionAsync(global::AlarmCenterGrpcServiceLibrary.StringArrRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExecuteSQLsWithTransactionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ExecuteSQLsWithTransactionAsync(global::AlarmCenterGrpcServiceLibrary.StringArrRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExecuteSQLsWithTransaction, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Listen(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Listen(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Listen(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Listen, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ListenAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ListenAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Listen, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Login(global::AlarmCenterGrpcServiceLibrary.LoginModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Login(global::AlarmCenterGrpcServiceLibrary.LoginModel request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> LoginAsync(global::AlarmCenterGrpcServiceLibrary.LoginModel request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> LoginAsync(global::AlarmCenterGrpcServiceLibrary.LoginModel request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CloseSession(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CloseSession(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CloseSession(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CloseSession, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CloseSessionAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CloseSessionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CloseSessionAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CloseSession, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.BaseResult DataRecordQueryFromXML(global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DataRecordQueryFromXML(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.BaseResult DataRecordQueryFromXML(global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DataRecordQueryFromXML, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.BaseResult> DataRecordQueryFromXMLAsync(global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DataRecordQueryFromXMLAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.BaseResult> DataRecordQueryFromXMLAsync(global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DataRecordQueryFromXML, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.ByteArrRequest OpenReadFromFile(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenReadFromFile(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.ByteArrRequest OpenReadFromFile(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_OpenReadFromFile, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> OpenReadFromFileAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenReadFromFileAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> OpenReadFromFileAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_OpenReadFromFile, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.ByteArrRequest ReadAllBytesFromFile(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadAllBytesFromFile(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.ByteArrRequest ReadAllBytesFromFile(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReadAllBytesFromFile, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> ReadAllBytesFromFileAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadAllBytesFromFileAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> ReadAllBytesFromFileAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReadAllBytesFromFile, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.BoolDefine ReadNextBuffer(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadNextBuffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.BoolDefine ReadNextBuffer(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReadNextBuffer, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.BoolDefine> ReadNextBufferAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadNextBufferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.BoolDefine> ReadNextBufferAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReadNextBuffer, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.ByteArrRequest GetCurrentBuffer(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCurrentBuffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.ByteArrRequest GetCurrentBuffer(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCurrentBuffer, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> GetCurrentBufferAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCurrentBufferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.ByteArrRequest> GetCurrentBufferAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCurrentBuffer, null, options, request);
      }
      /// <summary>
      ///rpc SetGUID (StringRequest) returns (google.protobuf.Empty);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply GetDatabaseType(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDatabaseType(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///rpc SetGUID (StringRequest) returns (google.protobuf.Empty);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply GetDatabaseType(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDatabaseType, null, options, request);
      }
      /// <summary>
      ///rpc SetGUID (StringRequest) returns (google.protobuf.Empty);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply> GetDatabaseTypeAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDatabaseTypeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///rpc SetGUID (StringRequest) returns (google.protobuf.Empty);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply> GetDatabaseTypeAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDatabaseType, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.BaseResult GetDataPagination(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataPagination(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.BaseResult GetDataPagination(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDataPagination, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.BaseResult> GetDataPaginationAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataPaginationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.BaseResult> GetDataPaginationAsync(global::AlarmCenterGrpcServiceLibrary.StringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDataPagination, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AlarmCenterDatabaseClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AlarmCenterDatabaseClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AlarmCenterDatabaseBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetDataTableOfEquip, serviceImpl.GetDataTableOfEquip)
          .AddMethod(__Method_GetObjectFromSQL, serviceImpl.GetObjectFromSQL)
          .AddMethod(__Method_GetDataTableOfYCP, serviceImpl.GetDataTableOfYCP)
          .AddMethod(__Method_GetDataTableOfYXP, serviceImpl.GetDataTableOfYXP)
          .AddMethod(__Method_GetDataTableOfSetParm, serviceImpl.GetDataTableOfSetParm)
          .AddMethod(__Method_GetDataTableFromSQL, serviceImpl.GetDataTableFromSQL)
          .AddMethod(__Method_GetDataTableFromSQLEx, serviceImpl.GetDataTableFromSQLEx)
          .AddMethod(__Method_GetDataTableFromSQLEx1, serviceImpl.GetDataTableFromSQLEx1)
          .AddMethod(__Method_GetDataAdapter, serviceImpl.GetDataAdapter)
          .AddMethod(__Method_SaveDataTableWithDataAdapter, serviceImpl.SaveDataTableWithDataAdapter)
          .AddMethod(__Method_ExecuteSQL, serviceImpl.ExecuteSQL)
          .AddMethod(__Method_ExecuteInsertSQL, serviceImpl.ExecuteInsertSQL)
          .AddMethod(__Method_ExecuteSQLsWithTransaction, serviceImpl.ExecuteSQLsWithTransaction)
          .AddMethod(__Method_Listen, serviceImpl.Listen)
          .AddMethod(__Method_Login, serviceImpl.Login)
          .AddMethod(__Method_CloseSession, serviceImpl.CloseSession)
          .AddMethod(__Method_DataRecordQueryFromXML, serviceImpl.DataRecordQueryFromXML)
          .AddMethod(__Method_OpenReadFromFile, serviceImpl.OpenReadFromFile)
          .AddMethod(__Method_ReadAllBytesFromFile, serviceImpl.ReadAllBytesFromFile)
          .AddMethod(__Method_ReadNextBuffer, serviceImpl.ReadNextBuffer)
          .AddMethod(__Method_GetCurrentBuffer, serviceImpl.GetCurrentBuffer)
          .AddMethod(__Method_GetDatabaseType, serviceImpl.GetDatabaseType)
          .AddMethod(__Method_GetDataPagination, serviceImpl.GetDataPagination).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AlarmCenterDatabaseBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetDataTableOfEquip, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(serviceImpl.GetDataTableOfEquip));
      serviceBinder.AddMethod(__Method_GetObjectFromSQL, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.GetObjectFromSQLReply>(serviceImpl.GetObjectFromSQL));
      serviceBinder.AddMethod(__Method_GetDataTableOfYCP, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(serviceImpl.GetDataTableOfYCP));
      serviceBinder.AddMethod(__Method_GetDataTableOfYXP, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(serviceImpl.GetDataTableOfYXP));
      serviceBinder.AddMethod(__Method_GetDataTableOfSetParm, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.EquipStaRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(serviceImpl.GetDataTableOfSetParm));
      serviceBinder.AddMethod(__Method_GetDataTableFromSQL, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.DataTableReply>(serviceImpl.GetDataTableFromSQL));
      serviceBinder.AddMethod(__Method_GetDataTableFromSQLEx, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.GetDataTableFromSQLEx));
      serviceBinder.AddMethod(__Method_GetDataTableFromSQLEx1, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.GetDataTableFromSQLEx1));
      serviceBinder.AddMethod(__Method_GetDataAdapter, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.GetDataAdapter));
      serviceBinder.AddMethod(__Method_SaveDataTableWithDataAdapter, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.DataTableReply, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SaveDataTableWithDataAdapter));
      serviceBinder.AddMethod(__Method_ExecuteSQL, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.IntegerRequest>(serviceImpl.ExecuteSQL));
      serviceBinder.AddMethod(__Method_ExecuteInsertSQL, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.ExecuteInsertSQLParm, global::AlarmCenterGrpcServiceLibrary.IntegerRequest>(serviceImpl.ExecuteInsertSQL));
      serviceBinder.AddMethod(__Method_ExecuteSQLsWithTransaction, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringArrRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.ExecuteSQLsWithTransaction));
      serviceBinder.AddMethod(__Method_Listen, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Listen));
      serviceBinder.AddMethod(__Method_Login, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.LoginModel, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Login));
      serviceBinder.AddMethod(__Method_CloseSession, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.CloseSession));
      serviceBinder.AddMethod(__Method_DataRecordQueryFromXML, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.DataRecordQueryFromXMLRequest, global::AlarmCenterGrpcServiceLibrary.BaseResult>(serviceImpl.DataRecordQueryFromXML));
      serviceBinder.AddMethod(__Method_OpenReadFromFile, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest>(serviceImpl.OpenReadFromFile));
      serviceBinder.AddMethod(__Method_ReadAllBytesFromFile, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest>(serviceImpl.ReadAllBytesFromFile));
      serviceBinder.AddMethod(__Method_ReadNextBuffer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.BoolDefine>(serviceImpl.ReadNextBuffer));
      serviceBinder.AddMethod(__Method_GetCurrentBuffer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.ByteArrRequest>(serviceImpl.GetCurrentBuffer));
      serviceBinder.AddMethod(__Method_GetDatabaseType, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AlarmCenterGrpcServiceLibrary.GetDatabaseTypeReply>(serviceImpl.GetDatabaseType));
      serviceBinder.AddMethod(__Method_GetDataPagination, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringRequest, global::AlarmCenterGrpcServiceLibrary.BaseResult>(serviceImpl.GetDataPagination));
    }

  }
}
#endregion
