// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/AlarmCenterEx.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AlarmCenterGrpcServiceLibrary {

  /// <summary>Holder for reflection information generated from proto/AlarmCenterEx.proto</summary>
  public static partial class AlarmCenterExReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/AlarmCenterEx.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AlarmCenterExReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chlwcm90by9BbGFybUNlbnRlckV4LnByb3RvEh1BbGFybUNlbnRlckdycGNT",
            "ZXJ2aWNlTGlicmFyeRobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGhJw",
            "cm90by9jb21tb24ucHJvdG8iawodU2V0UGFybUFycmF5V2FpdFJldHVyblJl",
            "cXVlc3QSOQoFSXRlbXMYASADKAsyKi5BbGFybUNlbnRlckdycGNTZXJ2aWNl",
            "TGlicmFyeS5TZXRQYXJtSXRlbRIPCgdzdHJVc2VyGAIgASgJIlMKC1NldFBh",
            "cm1JdGVtEhAKCGlFcXVpcE5vGAEgASgFEg4KBmlTZXRObxgCIAEoBRIQCghz",
            "dHJWYWx1ZRgDIAEoCRIQCghiU2hvd0RsZxgEIAEoCCJYChtTZXRQYXJtQXJy",
            "YXlXYWl0UmV0dXJuUmVwbHkSOQoFSXRlbXMYASADKAsyKi5BbGFybUNlbnRl",
            "ckdycGNTZXJ2aWNlTGlicmFyeS5TZXRQYXJtSXRlbTLwAQoNQWxhcm1DZW50",
            "ZXJFeBJKCgVMb2dpbhIpLkFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5",
            "LkxvZ2luTW9kZWwaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSkgEKFlNldFBh",
            "cm1BcnJheVdhaXRSZXR1cm4SPC5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGli",
            "cmFyeS5TZXRQYXJtQXJyYXlXYWl0UmV0dXJuUmVxdWVzdBo6LkFsYXJtQ2Vu",
            "dGVyR3JwY1NlcnZpY2VMaWJyYXJ5LlNldFBhcm1BcnJheVdhaXRSZXR1cm5S",
            "ZXBseUIgqgIdQWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnliBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::AlarmCenterGrpcServiceLibrary.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.SetParmArrayWaitReturnRequest), global::AlarmCenterGrpcServiceLibrary.SetParmArrayWaitReturnRequest.Parser, new[]{ "Items", "StrUser" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.SetParmItem), global::AlarmCenterGrpcServiceLibrary.SetParmItem.Parser, new[]{ "IEquipNo", "ISetNo", "StrValue", "BShowDlg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlarmCenterGrpcServiceLibrary.SetParmArrayWaitReturnReply), global::AlarmCenterGrpcServiceLibrary.SetParmArrayWaitReturnReply.Parser, new[]{ "Items" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SetParmArrayWaitReturnRequest : pb::IMessage<SetParmArrayWaitReturnRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SetParmArrayWaitReturnRequest> _parser = new pb::MessageParser<SetParmArrayWaitReturnRequest>(() => new SetParmArrayWaitReturnRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SetParmArrayWaitReturnRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterExReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetParmArrayWaitReturnRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetParmArrayWaitReturnRequest(SetParmArrayWaitReturnRequest other) : this() {
      items_ = other.items_.Clone();
      strUser_ = other.strUser_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetParmArrayWaitReturnRequest Clone() {
      return new SetParmArrayWaitReturnRequest(this);
    }

    /// <summary>Field number for the "Items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::AlarmCenterGrpcServiceLibrary.SetParmItem> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::AlarmCenterGrpcServiceLibrary.SetParmItem.Parser);
    private readonly pbc::RepeatedField<global::AlarmCenterGrpcServiceLibrary.SetParmItem> items_ = new pbc::RepeatedField<global::AlarmCenterGrpcServiceLibrary.SetParmItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::AlarmCenterGrpcServiceLibrary.SetParmItem> Items {
      get { return items_; }
    }

    /// <summary>Field number for the "strUser" field.</summary>
    public const int StrUserFieldNumber = 2;
    private string strUser_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StrUser {
      get { return strUser_; }
      set {
        strUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SetParmArrayWaitReturnRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SetParmArrayWaitReturnRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      if (StrUser != other.StrUser) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (StrUser.Length != 0) hash ^= StrUser.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (StrUser.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(StrUser);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (StrUser.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(StrUser);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (StrUser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrUser);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SetParmArrayWaitReturnRequest other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      if (other.StrUser.Length != 0) {
        StrUser = other.StrUser;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
          case 18: {
            StrUser = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
          case 18: {
            StrUser = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SetParmItem : pb::IMessage<SetParmItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SetParmItem> _parser = new pb::MessageParser<SetParmItem>(() => new SetParmItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SetParmItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterExReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetParmItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetParmItem(SetParmItem other) : this() {
      iEquipNo_ = other.iEquipNo_;
      iSetNo_ = other.iSetNo_;
      strValue_ = other.strValue_;
      bShowDlg_ = other.bShowDlg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetParmItem Clone() {
      return new SetParmItem(this);
    }

    /// <summary>Field number for the "iEquipNo" field.</summary>
    public const int IEquipNoFieldNumber = 1;
    private int iEquipNo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IEquipNo {
      get { return iEquipNo_; }
      set {
        iEquipNo_ = value;
      }
    }

    /// <summary>Field number for the "iSetNo" field.</summary>
    public const int ISetNoFieldNumber = 2;
    private int iSetNo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ISetNo {
      get { return iSetNo_; }
      set {
        iSetNo_ = value;
      }
    }

    /// <summary>Field number for the "strValue" field.</summary>
    public const int StrValueFieldNumber = 3;
    private string strValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StrValue {
      get { return strValue_; }
      set {
        strValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bShowDlg" field.</summary>
    public const int BShowDlgFieldNumber = 4;
    private bool bShowDlg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BShowDlg {
      get { return bShowDlg_; }
      set {
        bShowDlg_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SetParmItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SetParmItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IEquipNo != other.IEquipNo) return false;
      if (ISetNo != other.ISetNo) return false;
      if (StrValue != other.StrValue) return false;
      if (BShowDlg != other.BShowDlg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IEquipNo != 0) hash ^= IEquipNo.GetHashCode();
      if (ISetNo != 0) hash ^= ISetNo.GetHashCode();
      if (StrValue.Length != 0) hash ^= StrValue.GetHashCode();
      if (BShowDlg != false) hash ^= BShowDlg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IEquipNo != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IEquipNo);
      }
      if (ISetNo != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ISetNo);
      }
      if (StrValue.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StrValue);
      }
      if (BShowDlg != false) {
        output.WriteRawTag(32);
        output.WriteBool(BShowDlg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IEquipNo != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IEquipNo);
      }
      if (ISetNo != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ISetNo);
      }
      if (StrValue.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StrValue);
      }
      if (BShowDlg != false) {
        output.WriteRawTag(32);
        output.WriteBool(BShowDlg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IEquipNo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IEquipNo);
      }
      if (ISetNo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ISetNo);
      }
      if (StrValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrValue);
      }
      if (BShowDlg != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SetParmItem other) {
      if (other == null) {
        return;
      }
      if (other.IEquipNo != 0) {
        IEquipNo = other.IEquipNo;
      }
      if (other.ISetNo != 0) {
        ISetNo = other.ISetNo;
      }
      if (other.StrValue.Length != 0) {
        StrValue = other.StrValue;
      }
      if (other.BShowDlg != false) {
        BShowDlg = other.BShowDlg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IEquipNo = input.ReadInt32();
            break;
          }
          case 16: {
            ISetNo = input.ReadInt32();
            break;
          }
          case 26: {
            StrValue = input.ReadString();
            break;
          }
          case 32: {
            BShowDlg = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IEquipNo = input.ReadInt32();
            break;
          }
          case 16: {
            ISetNo = input.ReadInt32();
            break;
          }
          case 26: {
            StrValue = input.ReadString();
            break;
          }
          case 32: {
            BShowDlg = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SetParmArrayWaitReturnReply : pb::IMessage<SetParmArrayWaitReturnReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SetParmArrayWaitReturnReply> _parser = new pb::MessageParser<SetParmArrayWaitReturnReply>(() => new SetParmArrayWaitReturnReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SetParmArrayWaitReturnReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlarmCenterGrpcServiceLibrary.AlarmCenterExReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetParmArrayWaitReturnReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetParmArrayWaitReturnReply(SetParmArrayWaitReturnReply other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetParmArrayWaitReturnReply Clone() {
      return new SetParmArrayWaitReturnReply(this);
    }

    /// <summary>Field number for the "Items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::AlarmCenterGrpcServiceLibrary.SetParmItem> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::AlarmCenterGrpcServiceLibrary.SetParmItem.Parser);
    private readonly pbc::RepeatedField<global::AlarmCenterGrpcServiceLibrary.SetParmItem> items_ = new pbc::RepeatedField<global::AlarmCenterGrpcServiceLibrary.SetParmItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::AlarmCenterGrpcServiceLibrary.SetParmItem> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SetParmArrayWaitReturnReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SetParmArrayWaitReturnReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SetParmArrayWaitReturnReply other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
