// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/CallbackContract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AlarmCenterGrpcServiceLibrary {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class CallbackContract
  {
    static readonly string __ServiceName = "AlarmCenterGrpcServiceLibrary.CallbackContract";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.ShowInfoRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_ShowInfoRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.ShowInfoRequest.Parser));
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.ShowLockSetParmMsgRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_ShowLockSetParmMsgRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.ShowLockSetParmMsgRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.ShowOrClosePageRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_ShowOrClosePageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.ShowOrClosePageRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.OpenPage4InterScreenRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_OpenPage4InterScreenRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.OpenPage4InterScreenRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.GetAllPageRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_GetAllPageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.GetAllPageRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.ActionRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_ActionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.ActionRequest.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.BoolDefine> __Marshaller_AlarmCenterGrpcServiceLibrary_BoolDefine = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.BoolDefine.Parser));
    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.GetClientInfoRequest> __Marshaller_AlarmCenterGrpcServiceLibrary_GetClientInfoRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.GetClientInfoRequest.Parser));

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.ShowInfoRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ShowInfo = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.ShowInfoRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ShowInfo",
        __Marshaller_AlarmCenterGrpcServiceLibrary_ShowInfoRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.ShowLockSetParmMsgRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ShowLockSetParmMsg = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.ShowLockSetParmMsgRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ShowLockSetParmMsg",
        __Marshaller_AlarmCenterGrpcServiceLibrary_ShowLockSetParmMsgRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.ShowOrClosePageRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ShowOrClosePage = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.ShowOrClosePageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ShowOrClosePage",
        __Marshaller_AlarmCenterGrpcServiceLibrary_ShowOrClosePageRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.OpenPage4InterScreenRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_OpenPage4InterScreen = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.OpenPage4InterScreenRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "OpenPage4InterScreen",
        __Marshaller_AlarmCenterGrpcServiceLibrary_OpenPage4InterScreenRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.GetAllPageRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_GetAllPage = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.GetAllPageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAllPage",
        __Marshaller_AlarmCenterGrpcServiceLibrary_GetAllPageRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.ActionRequest, global::AlarmCenterGrpcServiceLibrary.BoolDefine> __Method_Action = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.ActionRequest, global::AlarmCenterGrpcServiceLibrary.BoolDefine>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Action",
        __Marshaller_AlarmCenterGrpcServiceLibrary_ActionRequest,
        __Marshaller_AlarmCenterGrpcServiceLibrary_BoolDefine);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.GetClientInfoRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_GetClientInfo = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.GetClientInfoRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetClientInfo",
        __Marshaller_AlarmCenterGrpcServiceLibrary_GetClientInfoRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AlarmCenterGrpcServiceLibrary.CallbackContractReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CallbackContract</summary>
    [grpc::BindServiceMethod(typeof(CallbackContract), "BindService")]
    public abstract partial class CallbackContractBase
    {
      public virtual global::System.Threading.Tasks.Task ShowInfo(global::AlarmCenterGrpcServiceLibrary.ShowInfoRequest request, grpc::IServerStreamWriter<global::Google.Protobuf.WellKnownTypes.Empty> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ShowLockSetParmMsg(global::AlarmCenterGrpcServiceLibrary.ShowLockSetParmMsgRequest request, grpc::IServerStreamWriter<global::Google.Protobuf.WellKnownTypes.Empty> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ShowOrClosePage(global::AlarmCenterGrpcServiceLibrary.ShowOrClosePageRequest request, grpc::IServerStreamWriter<global::Google.Protobuf.WellKnownTypes.Empty> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task OpenPage4InterScreen(global::AlarmCenterGrpcServiceLibrary.OpenPage4InterScreenRequest request, grpc::IServerStreamWriter<global::Google.Protobuf.WellKnownTypes.Empty> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task GetAllPage(global::AlarmCenterGrpcServiceLibrary.GetAllPageRequest request, grpc::IServerStreamWriter<global::Google.Protobuf.WellKnownTypes.Empty> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Action(global::AlarmCenterGrpcServiceLibrary.ActionRequest request, grpc::IServerStreamWriter<global::AlarmCenterGrpcServiceLibrary.BoolDefine> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task GetClientInfo(global::AlarmCenterGrpcServiceLibrary.GetClientInfoRequest request, grpc::IServerStreamWriter<global::Google.Protobuf.WellKnownTypes.Empty> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CallbackContract</summary>
    public partial class CallbackContractClient : grpc::ClientBase<CallbackContractClient>
    {
      /// <summary>Creates a new client for CallbackContract</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CallbackContractClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CallbackContract that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CallbackContractClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CallbackContractClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CallbackContractClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> ShowInfo(global::AlarmCenterGrpcServiceLibrary.ShowInfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShowInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> ShowInfo(global::AlarmCenterGrpcServiceLibrary.ShowInfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ShowInfo, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> ShowLockSetParmMsg(global::AlarmCenterGrpcServiceLibrary.ShowLockSetParmMsgRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShowLockSetParmMsg(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> ShowLockSetParmMsg(global::AlarmCenterGrpcServiceLibrary.ShowLockSetParmMsgRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ShowLockSetParmMsg, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> ShowOrClosePage(global::AlarmCenterGrpcServiceLibrary.ShowOrClosePageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShowOrClosePage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> ShowOrClosePage(global::AlarmCenterGrpcServiceLibrary.ShowOrClosePageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ShowOrClosePage, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> OpenPage4InterScreen(global::AlarmCenterGrpcServiceLibrary.OpenPage4InterScreenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenPage4InterScreen(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> OpenPage4InterScreen(global::AlarmCenterGrpcServiceLibrary.OpenPage4InterScreenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_OpenPage4InterScreen, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> GetAllPage(global::AlarmCenterGrpcServiceLibrary.GetAllPageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllPage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> GetAllPage(global::AlarmCenterGrpcServiceLibrary.GetAllPageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAllPage, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.BoolDefine> Action(global::AlarmCenterGrpcServiceLibrary.ActionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Action(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::AlarmCenterGrpcServiceLibrary.BoolDefine> Action(global::AlarmCenterGrpcServiceLibrary.ActionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Action, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> GetClientInfo(global::AlarmCenterGrpcServiceLibrary.GetClientInfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetClientInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Google.Protobuf.WellKnownTypes.Empty> GetClientInfo(global::AlarmCenterGrpcServiceLibrary.GetClientInfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetClientInfo, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CallbackContractClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CallbackContractClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CallbackContractBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ShowInfo, serviceImpl.ShowInfo)
          .AddMethod(__Method_ShowLockSetParmMsg, serviceImpl.ShowLockSetParmMsg)
          .AddMethod(__Method_ShowOrClosePage, serviceImpl.ShowOrClosePage)
          .AddMethod(__Method_OpenPage4InterScreen, serviceImpl.OpenPage4InterScreen)
          .AddMethod(__Method_GetAllPage, serviceImpl.GetAllPage)
          .AddMethod(__Method_Action, serviceImpl.Action)
          .AddMethod(__Method_GetClientInfo, serviceImpl.GetClientInfo).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CallbackContractBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ShowInfo, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.ShowInfoRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.ShowInfo));
      serviceBinder.AddMethod(__Method_ShowLockSetParmMsg, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.ShowLockSetParmMsgRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.ShowLockSetParmMsg));
      serviceBinder.AddMethod(__Method_ShowOrClosePage, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.ShowOrClosePageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.ShowOrClosePage));
      serviceBinder.AddMethod(__Method_OpenPage4InterScreen, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.OpenPage4InterScreenRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.OpenPage4InterScreen));
      serviceBinder.AddMethod(__Method_GetAllPage, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.GetAllPageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.GetAllPage));
      serviceBinder.AddMethod(__Method_Action, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.ActionRequest, global::AlarmCenterGrpcServiceLibrary.BoolDefine>(serviceImpl.Action));
      serviceBinder.AddMethod(__Method_GetClientInfo, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AlarmCenterGrpcServiceLibrary.GetClientInfoRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.GetClientInfo));
    }

  }
}
#endregion
