// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/MultiStation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AlarmCenterGrpcServiceLibrary {

  /// <summary>Holder for reflection information generated from proto/MultiStation.proto</summary>
  public static partial class MultiStationReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/MultiStation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MultiStationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhwcm90by9NdWx0aVN0YXRpb24ucHJvdG8SHUFsYXJtQ2VudGVyR3JwY1Nl",
            "cnZpY2VMaWJyYXJ5Ghtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8ygwEK",
            "DE11bHRpU3RhdGlvbhI4CgZMaXN0ZW4SFi5nb29nbGUucHJvdG9idWYuRW1w",
            "dHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSOQoHQ29ubmVjdBIWLmdvb2ds",
            "ZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eUIgqgId",
            "QWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
