// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/SingleStationCallback.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AlarmCenterGrpcServiceLibrary {

  /// <summary>Holder for reflection information generated from proto/SingleStationCallback.proto</summary>
  public static partial class SingleStationCallbackReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/SingleStationCallback.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SingleStationCallbackReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFwcm90by9TaW5nbGVTdGF0aW9uQ2FsbGJhY2sucHJvdG8SHUFsYXJtQ2Vu",
            "dGVyR3JwY1NlcnZpY2VMaWJyYXJ5Ghtnb29nbGUvcHJvdG9idWYvZW1wdHku",
            "cHJvdG8aEnByb3RvL2NvbW1vbi5wcm90bzLbBgoVU2luZ2xlU3RhdGlvbkNh",
            "bGxiYWNrEkkKF0dldFRvdGFsUlRFcXVpcEl0ZW1EYXRhEhYuZ29vZ2xlLnBy",
            "b3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EkYKFEdldFRv",
            "dGFsUlRZQ0l0ZW1EYXRhEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29v",
            "Z2xlLnByb3RvYnVmLkVtcHR5EkYKFEdldFRvdGFsUlRZWEl0ZW1EYXRhEhYu",
            "Z29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5",
            "EksKGUdldENoYW5nZWRSVEVxdWlwSXRlbURhdGESFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSSAoWR2V0Q2hhbmdl",
            "ZFJUWUNJdGVtRGF0YRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2ds",
            "ZS5wcm90b2J1Zi5FbXB0eRJIChZHZXRDaGFuZ2VkUlRZWEl0ZW1EYXRhEhYu",
            "Z29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5",
            "ElAKB1NldFBhcm0SLS5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5T",
            "ZXRQYXJtUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRJACg5SZWFk",
            "TmV4dEJ1ZmZlchIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5w",
            "cm90b2J1Zi5FbXB0eRJCChBHZXRDdXJyZW50QnVmZmVyEhYuZ29vZ2xlLnBy",
            "b3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EmkKD0RsbFJl",
            "Z2lzdGVyRGF0YRIrLkFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LlN0",
            "cmluZ1Jlc3VsdBopLkFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LkJv",
            "b2xEZWZpbmUSQwoRU2V0VmFyaWFibGVzMk51bGwSFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHlCIKoCHUFsYXJtQ2Vu",
            "dGVyR3JwY1NlcnZpY2VMaWJyYXJ5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::AlarmCenterGrpcServiceLibrary.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
