// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/SystemManage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AlarmCenterGrpcServiceLibrary {

  /// <summary>Holder for reflection information generated from proto/SystemManage.proto</summary>
  public static partial class SystemManageReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/SystemManage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SystemManageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhwcm90by9TeXN0ZW1NYW5hZ2UucHJvdG8SHUFsYXJtQ2VudGVyR3JwY1Nl",
            "cnZpY2VMaWJyYXJ5GhJwcm90by9jb21tb24ucHJvdG8aG2dvb2dsZS9wcm90",
            "b2J1Zi9lbXB0eS5wcm90bzKnCAoMU3lzdGVtTWFuYWdlEmEKB0FkZFJvbGUS",
            "Ky5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5TdHJpbmdSZXN1bHQa",
            "KS5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5Cb29sRGVmaW5lEmQK",
            "CkRlbGV0ZVJvbGUSKy5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5T",
            "dHJpbmdSZXN1bHQaKS5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5C",
            "b29sRGVmaW5lEmkKD0dldFJvbGVFbnRpdGllcxIrLkFsYXJtQ2VudGVyR3Jw",
            "Y1NlcnZpY2VMaWJyYXJ5LlN0cmluZ1Jlc3VsdBopLkFsYXJtQ2VudGVyR3Jw",
            "Y1NlcnZpY2VMaWJyYXJ5LkJhc2VSZXN1bHQSZAoKTW9kaWZ5Um9sZRIrLkFs",
            "YXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LlN0cmluZ1Jlc3VsdBopLkFs",
            "YXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LkJvb2xEZWZpbmUSaQoPR2V0",
            "VXNlckVudGl0aWVzEisuQWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnku",
            "U3RyaW5nUmVzdWx0GikuQWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnku",
            "QmFzZVJlc3VsdBJmCgpHZXRXZWJVc2VyEisuQWxhcm1DZW50ZXJHcnBjU2Vy",
            "dmljZUxpYnJhcnkuU3RyaW5nUmVzdWx0GisuQWxhcm1DZW50ZXJHcnBjU2Vy",
            "dmljZUxpYnJhcnkuU3RyaW5nUmVzdWx0EmcKDUFkZFVzZXJFbnRpdHkSKy5B",
            "bGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5TdHJpbmdSZXN1bHQaKS5B",
            "bGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeS5Cb29sRGVmaW5lEmsKEERl",
            "bGV0ZVVzZXJFbnRpdHkSLC5BbGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFy",
            "eS5JbnRlZ2VyRGVmaW5lGikuQWxhcm1DZW50ZXJHcnBjU2VydmljZUxpYnJh",
            "cnkuQm9vbERlZmluZRJqChBNb2RpZnlVc2VyRW50aXR5EisuQWxhcm1DZW50",
            "ZXJHcnBjU2VydmljZUxpYnJhcnkuU3RyaW5nUmVzdWx0GikuQWxhcm1DZW50",
            "ZXJHcnBjU2VydmljZUxpYnJhcnkuQm9vbERlZmluZRJoCg5SZXZpc2VQYXNz",
            "d29yZBIrLkFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LlN0cmluZ1Jl",
            "c3VsdBopLkFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5LkJvb2xEZWZp",
            "bmVCIKoCHUFsYXJtQ2VudGVyR3JwY1NlcnZpY2VMaWJyYXJ5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AlarmCenterGrpcServiceLibrary.CommonReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
