// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/Tool.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AlarmCenterGrpcServiceLibrary {

  /// <summary>Holder for reflection information generated from proto/Tool.proto</summary>
  public static partial class ToolReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/Tool.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ToolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBwcm90by9Ub29sLnByb3RvEh1BbGFybUNlbnRlckdycGNTZXJ2aWNlTGli",
            "cmFyeRoScHJvdG8vY29tbW9uLnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1w",
            "dHkucHJvdG8y0AEKBFRvb2wSYwoHRW5jcnlwdBIrLkFsYXJtQ2VudGVyR3Jw",
            "Y1NlcnZpY2VMaWJyYXJ5LlN0cmluZ1Jlc3VsdBorLkFsYXJtQ2VudGVyR3Jw",
            "Y1NlcnZpY2VMaWJyYXJ5LlN0cmluZ1Jlc3VsdBJjCgdEZWNyeXB0EisuQWxh",
            "cm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnkuU3RyaW5nUmVzdWx0GisuQWxh",
            "cm1DZW50ZXJHcnBjU2VydmljZUxpYnJhcnkuU3RyaW5nUmVzdWx0QiCqAh1B",
            "bGFybUNlbnRlckdycGNTZXJ2aWNlTGlicmFyeWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AlarmCenterGrpcServiceLibrary.CommonReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
