// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/Tool.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AlarmCenterGrpcServiceLibrary {
  public static partial class Tool
  {
    static readonly string __ServiceName = "AlarmCenterGrpcServiceLibrary.Tool";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::AlarmCenterGrpcServiceLibrary.StringResult> __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AlarmCenterGrpcServiceLibrary.StringResult.Parser));

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringResult, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_Encrypt = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringResult, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Encrypt",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    static readonly grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringResult, global::AlarmCenterGrpcServiceLibrary.StringResult> __Method_Decrypt = new grpc::Method<global::AlarmCenterGrpcServiceLibrary.StringResult, global::AlarmCenterGrpcServiceLibrary.StringResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Decrypt",
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult,
        __Marshaller_AlarmCenterGrpcServiceLibrary_StringResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AlarmCenterGrpcServiceLibrary.ToolReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Tool</summary>
    [grpc::BindServiceMethod(typeof(Tool), "BindService")]
    public abstract partial class ToolBase
    {
      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.StringResult> Encrypt(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::AlarmCenterGrpcServiceLibrary.StringResult> Decrypt(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Tool</summary>
    public partial class ToolClient : grpc::ClientBase<ToolClient>
    {
      /// <summary>Creates a new client for Tool</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ToolClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Tool that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ToolClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ToolClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ToolClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult Encrypt(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Encrypt(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult Encrypt(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Encrypt, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> EncryptAsync(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EncryptAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> EncryptAsync(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Encrypt, null, options, request);
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult Decrypt(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Decrypt(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::AlarmCenterGrpcServiceLibrary.StringResult Decrypt(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Decrypt, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> DecryptAsync(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DecryptAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::AlarmCenterGrpcServiceLibrary.StringResult> DecryptAsync(global::AlarmCenterGrpcServiceLibrary.StringResult request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Decrypt, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ToolClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ToolClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ToolBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Encrypt, serviceImpl.Encrypt)
          .AddMethod(__Method_Decrypt, serviceImpl.Decrypt).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ToolBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Encrypt, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringResult, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.Encrypt));
      serviceBinder.AddMethod(__Method_Decrypt, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AlarmCenterGrpcServiceLibrary.StringResult, global::AlarmCenterGrpcServiceLibrary.StringResult>(serviceImpl.Decrypt));
    }

  }
}
#endregion
